version: '3.8'

services:
  app:
    container_name: fastapi-todo-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  db:
    container_name: fastapi-todo-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
